version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      VIRTUAL_HOST: my-app.local
      VIRTUAL_PORT: 3000
    expose:
      - 3000
networks:
  default:
    external:
      name: nginx-proxy